### ISSUE TITLE
Model training issue

### ISSUE THREAD

**Issue by AnushaManila** [mlberkeley/Creative-Adversarial-Networks#1]
After downloading the wiki-art dataset, I tried to train the model by editing the parameters in train.sh
The generated samples seem to be not correct.
Please find the attached sample image generated.
![test_arange_99](https://user-images.githubusercontent.com/12676003/31943633-9320e3ac-b8c9-11e7-804b-3596ffd64101.png)

Reducing the learning rate also produced similar images.
Any suggestions would be nice.
Thank you.

**Comment by philkuz** [comment]
We're still working on this repo. We'd happily take any PRs if you find something that works!

**Comment by philkuz** [comment]
Closing for now. Feel free to open this again if you still have this issue when we remove the (WIP) tag.
