### ISSUE TITLE
dimension of sample_inputs and self.inputs

### ISSUE THREAD

**Issue by jd730** [mlberkeley/Creative-Adversarial-Networks#2]
I got a problem that
```  File "main.py", line 123, in <module>
    tf.app.run()
  File "/home/jd730/p3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 114, in main
    dcgan.train(FLAGS)
  File "/home/jd730/Creative-Adversarial-Networks/model.py", line 402, in train
    self.y:sample_labels,
  File "/home/jd730/p3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/jd730/p3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64, 64, 64, 3) for Tensor 'real_images:0', which has shape '(36, 64, 64, 3)'
```
I think its because difference of dimension of self.inputs and samples_inputs.
In model.py

According to line 117, self.inputs should be [batch_size,  image_dims(ex. 64 64 3)]
`    self.inputs = tf.placeholder(tf.float32, [self.batch_size] + image_dims, name='real_images')`

However, on line 237, `sample_inputs` which is a factor of `self.inputs` on line 398 is defined by 
```      sample_files = self.data[0:self.sample_num]
      sample = [
          get_image(sample_file,
                    input_height=self.input_height,
                    input_width=self.input_width,
                    resize_height=self.output_height,
                    resize_width=self.output_width,
                    crop=self.crop,
                    grayscale=self.grayscale) for sample_file in sample_files]
      if (self.grayscale):
        sample_inputs = np.array(sample).astype(np.float32)[:, :, :, None]
      else:
        sample_inputs = np.array(sample).astype(np.float32)
```

So, its dimension is [sample_num(=sample_size), image_dim] .

I thought it should change to `batch_size` rather `sample_num`. But, carpedm20's DCGAN also used that code. 
May I ask if you can explain this situation?

**Comment by phillip-kravtsov** [comment]
Hi - this repo is a work in progress and there's still a good amount of work to be done. In general, there are a number of functionalities which don't yet work properly.

The original DCGAN code doesn't support different sizes for batch and sample sizes, and sets them equal to each other when creating the DCGAN object. We've added some code to support different sample and batch sizes, and this particular portion of the code should work properly. Let us know if this doesn't solve the problem for you.

**Comment by jd730** [comment]
Thank you for answering. Oh I found that DCGAN puts FLAGS.batch_size to sample_num. 

 What you mean is the model at least work well in that code although batch size is 64 and sample size is 36?

Could you tell me where is to make this happen?
I think, although self.inputs is made by placeholder of which first dimension is None, the dimensionality issue may occur in train function in my case. I will try to find the cause and solution.

Your code
https://github.com/mlberkeley/Creative-Adversarial-Networks/blob/e66f9577d9990b093444c1cfd5162e1a1648a4a4/model.py#L118

DCGAN was assigned by batch_size
https://github.com/carpedm20/DCGAN-tensorflow/blob/b138300623b933e2076872e7f812ba553e862355/model.py#L99


 Thank you.

**Comment by phillip-kravtsov** [comment]
If you pull the new code from the repository, which has been updated since you asked your question, and run train.sh with different values for batch_size and sample_size, the code should not throw an error and should behave as expected.
There shouldn't be any dimensionality issues (there weren't when I tested it). 

The original DCGAN code assumed that batch_size and sample_size were the same.

**Comment by jd730** [comment]
Thank you I will try it later. :)
Frankly, I did not notice your latest push. Sorry about that.

**Comment by galoisgroupcn** [comment]
@jd730 Hi Jaedong, did you successfully run it on your own?

Thanks,
Amber

**Comment by jd730** [comment]
@galoisgroupcn  Hi, 
Actually, I am not sure whether I could run it or not. However, I remember that I ran it when I set the dimension correctly.

**Comment by galoisgroupcn** [comment]
@jd730 Hi Jaedong, are you still interested in this repo? I'm working on it on Google Colab. Would you like to work together? I can exchange code of my Colab Notebook. Thank you!

Best,

Amber Ji

**Comment by jd730** [comment]
@galoisgroupcn  Hi,
 I am good. 

 Thank you.
Jaedong
