### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by ruotianluo** [mlberkeley/Creative-Adversarial-Networks#22]
After I downloaded the zip file from https://github.com/cs-chan/ICIP2016-PC/tree/f5d6f6b58a6d8a4bd05aaaedd9688d08c02df8f2/WikiArt%20Dataset, and ran the training script, it says vincent-van-gogh_l-arlesienne-portrait-of-madame-ginoux-1890.jpg is broken.

How did you deal with that? (I saw you have check_images.py. How do you actually use it)

**Comment by phillip-kravtsov** [comment]
That was the same image we had issues with. check_images.py doesn't delete the image, so we manually deleted it from our filesystem.
We didn't have any issues with any other images, thanks for letting us know!

**Comment by ruotianluo** [comment]
Thanks.
