### ISSUE TITLE
On Google Colab

### ISSUE THREAD

**Issue by galoisgroupcn** [mlberkeley/Creative-Adversarial-Networks#28]
Hi,

Has anyone tried running the whole program on Google Colab?

If I choose to run on Google Colab,  do I need to modify lots of code (e.g. location of files...) ? Or can I just 'git clone' and go?

@pilkuz @phillip-kravtsov Which Nvidia GPU were you guys using when running the program? Nvidia GTX 1060?

Thanks very much!

**Comment by andre-fu** [comment]
@galoisgroupcn hello, I'm also trying to run this model on Colab, did you find any headway?
